version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: securelog-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: securelog
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: securelog-server
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/securelog
    depends_on:
      - postgres

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: securelog-web
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  pgdata:
